package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerNotifications;
 
/**
 * DAO interface for table: TrackerNotifications.
 * @author autogenerated
 */
public interface TrackerNotificationsDao extends GenericDAO<TrackerNotifications,  Integer>  {
	// constructor only
}

