package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerPrefs;
 
/**
 * DAO interface for table: TrackerPrefs.
 * @author autogenerated
 */
public interface TrackerPrefsDao extends GenericDAO<TrackerPrefs,  Integer>  {
	// constructor only
}

