package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerProjects;
 
/**
 * DAO interface for table: TrackerProjects.
 * @author autogenerated
 */
public interface TrackerProjectsDao extends GenericDAO<TrackerProjects,  Integer>  {
	// constructor only
}

