package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerDependencies;
 
/**
 * DAO interface for table: TrackerDependencies.
 * @author autogenerated
 */
public interface TrackerDependenciesDao extends GenericDAO<TrackerDependencies,  Integer>  {
	// constructor only
}

