package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerNotificationRecipients;
 
/**
 * DAO interface for table: TrackerNotificationRecipients.
 * @author autogenerated
 */
public interface TrackerNotificationRecipientsDao extends GenericDAO<TrackerNotificationRecipients,  Integer>  {
	// constructor only
}

