package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerComments;
 
/**
 * DAO interface for table: TrackerComments.
 * @author autogenerated
 */
public interface TrackerCommentsDao extends GenericDAO<TrackerComments,  Integer>  {
	// constructor only
}

