package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerCity;
 
/**
 * DAO interface for table: TrackerCity.
 * @author autogenerated
 */
public interface TrackerCityDao extends GenericDAO<TrackerCity,  Integer>  {
	// constructor only
}

