package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListCategory;
 
/**
 * DAO interface for table: TrackerListCategory.
 * @author autogenerated
 */
public interface TrackerListCategoryDao extends GenericDAO<TrackerListCategory,  Integer>  {
	// constructor only
}

