package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListVersion;
 
/**
 * DAO interface for table: TrackerListVersion.
 * @author autogenerated
 */
public interface TrackerListVersionDao extends GenericDAO<TrackerListVersion,  Integer>  {
	// constructor only
}

