package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerTasks;
 
/**
 * DAO interface for table: TrackerTasks.
 * @author autogenerated
 */
public interface TrackerTasksDao extends GenericDAO<TrackerTasks,  Integer>  {
	// constructor only
}

