package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUsers;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerUsersDao;
 
 
/**
 * DAO for table: TrackerUsers.
 * @author autogenerated
 */
@Repository
public class TrackerUsersDaoImpl extends GenericHibernateDaoImpl<TrackerUsers, Integer> implements TrackerUsersDao {
	
	/** Constructor method. */
		public TrackerUsersDaoImpl() {
			super(TrackerUsers.class);
		}
	}

