package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListCategory;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerListCategoryDao;
 
 
/**
 * DAO for table: TrackerListCategory.
 * @author autogenerated
 */
@Repository
public class TrackerListCategoryDaoImpl extends GenericHibernateDaoImpl<TrackerListCategory, Integer> implements TrackerListCategoryDao {
	
	/** Constructor method. */
		public TrackerListCategoryDaoImpl() {
			super(TrackerListCategory.class);
		}
	}

