package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerReminders;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerRemindersDao;
 
 
/**
 * DAO for table: TrackerReminders.
 * @author autogenerated
 */
@Repository
public class TrackerRemindersDaoImpl extends GenericHibernateDaoImpl<TrackerReminders, Integer> implements TrackerRemindersDao {
	
	/** Constructor method. */
		public TrackerRemindersDaoImpl() {
			super(TrackerReminders.class);
		}
	}

