package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUserSession;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerUserSessionDao;
 
 
/**
 * DAO for table: TrackerUserSession.
 * @author autogenerated
 */
@Repository
public class TrackerUserSessionDaoImpl extends GenericHibernateDaoImpl<TrackerUserSession, Integer> implements TrackerUserSessionDao {
	
	/** Constructor method. */
		public TrackerUserSessionDaoImpl() {
			super(TrackerUserSession.class);
		}
	}

