package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerPrefs;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerPrefsDao;
 
 
/**
 * DAO for table: TrackerPrefs.
 * @author autogenerated
 */
@Repository
public class TrackerPrefsDaoImpl extends GenericHibernateDaoImpl<TrackerPrefs, Integer> implements TrackerPrefsDao {
	
	/** Constructor method. */
		public TrackerPrefsDaoImpl() {
			super(TrackerPrefs.class);
		}
	}

