package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerCity;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerCityDao;
 
 
/**
 * DAO for table: TrackerCity.
 * @author autogenerated
 */
@Repository
public class TrackerCityDaoImpl extends GenericHibernateDaoImpl<TrackerCity, Integer> implements TrackerCityDao {
	
	/** Constructor method. */
		public TrackerCityDaoImpl() {
			super(TrackerCity.class);
		}
	}

