package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListTasktype;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerListTasktypeDao;
 
 
/**
 * DAO for table: TrackerListTasktype.
 * @author autogenerated
 */
@Repository
public class TrackerListTasktypeDaoImpl extends GenericHibernateDaoImpl<TrackerListTasktype, Integer> implements TrackerListTasktypeDao {
	
	/** Constructor method. */
		public TrackerListTasktypeDaoImpl() {
			super(TrackerListTasktype.class);
		}
	}

