package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerComments;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerCommentsDao;
 
 
/**
 * DAO for table: TrackerComments.
 * @author autogenerated
 */
@Repository
public class TrackerCommentsDaoImpl extends GenericHibernateDaoImpl<TrackerComments, Integer> implements TrackerCommentsDao {
	
	/** Constructor method. */
		public TrackerCommentsDaoImpl() {
			super(TrackerComments.class);
		}
	}

