package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListResolution;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerListResolutionDao;
 
 
/**
 * DAO for table: TrackerListResolution.
 * @author autogenerated
 */
@Repository
public class TrackerListResolutionDaoImpl extends GenericHibernateDaoImpl<TrackerListResolution, Integer> implements TrackerListResolutionDao {
	
	/** Constructor method. */
		public TrackerListResolutionDaoImpl() {
			super(TrackerListResolution.class);
		}
	}

