package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerTasks;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerTasksDao;
 
 
/**
 * DAO for table: TrackerTasks.
 * @author autogenerated
 */
@Repository
public class TrackerTasksDaoImpl extends GenericHibernateDaoImpl<TrackerTasks, Integer> implements TrackerTasksDao {
	
	/** Constructor method. */
		public TrackerTasksDaoImpl() {
			super(TrackerTasks.class);
		}
	}

