package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerGroups;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerGroupsDao;
 
 
/**
 * DAO for table: TrackerGroups.
 * @author autogenerated
 */
@Repository
public class TrackerGroupsDaoImpl extends GenericHibernateDaoImpl<TrackerGroups, Integer> implements TrackerGroupsDao {
	
	/** Constructor method. */
		public TrackerGroupsDaoImpl() {
			super(TrackerGroups.class);
		}
	}

