package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerTableChangeLog;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerTableChangeLogDao;
 
 
/**
 * DAO for table: TrackerTableChangeLog.
 * @author autogenerated
 */
@Repository
public class TrackerTableChangeLogDaoImpl extends GenericHibernateDaoImpl<TrackerTableChangeLog, Integer> implements TrackerTableChangeLogDao {
	
	/** Constructor method. */
		public TrackerTableChangeLogDaoImpl() {
			super(TrackerTableChangeLog.class);
		}
	}

