package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerSearches;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerSearchesDao;
 
 
/**
 * DAO for table: TrackerSearches.
 * @author autogenerated
 */
@Repository
public class TrackerSearchesDaoImpl extends GenericHibernateDaoImpl<TrackerSearches, Integer> implements TrackerSearchesDao {
	
	/** Constructor method. */
		public TrackerSearchesDaoImpl() {
			super(TrackerSearches.class);
		}
	}

