package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAssignedOld;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerAssignedOldDao;
 
 
/**
 * DAO for table: TrackerAssignedOld.
 * @author autogenerated
 */
@Repository
public class TrackerAssignedOldDaoImpl extends GenericHibernateDaoImpl<TrackerAssignedOld, Integer> implements TrackerAssignedOldDao {
	
	/** Constructor method. */
		public TrackerAssignedOldDaoImpl() {
			super(TrackerAssignedOld.class);
		}
	}

