package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUserMobileSetting;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerUserMobileSettingDao;
 
 
/**
 * DAO for table: TrackerUserMobileSetting.
 * @author autogenerated
 */
@Repository
public class TrackerUserMobileSettingDaoImpl extends GenericHibernateDaoImpl<TrackerUserMobileSetting, Integer> implements TrackerUserMobileSettingDao {
	
	/** Constructor method. */
		public TrackerUserMobileSettingDaoImpl() {
			super(TrackerUserMobileSetting.class);
		}
	}

