package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerProjects;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerProjectsDao;
 
 
/**
 * DAO for table: TrackerProjects.
 * @author autogenerated
 */
@Repository
public class TrackerProjectsDaoImpl extends GenericHibernateDaoImpl<TrackerProjects, Integer> implements TrackerProjectsDao {
	
	/** Constructor method. */
		public TrackerProjectsDaoImpl() {
			super(TrackerProjects.class);
		}
	}

