package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListOs;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerListOsDao;
 
 
/**
 * DAO for table: TrackerListOs.
 * @author autogenerated
 */
@Repository
public class TrackerListOsDaoImpl extends GenericHibernateDaoImpl<TrackerListOs, Integer> implements TrackerListOsDao {
	
	/** Constructor method. */
		public TrackerListOsDaoImpl() {
			super(TrackerListOs.class);
		}
	}

