package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAssigned;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerAssignedDao;
 
 
/**
 * DAO for table: TrackerAssigned.
 * @author autogenerated
 */
@Repository
public class TrackerAssignedDaoImpl extends GenericHibernateDaoImpl<TrackerAssigned, Integer> implements TrackerAssignedDao {
	
	/** Constructor method. */
		public TrackerAssignedDaoImpl() {
			super(TrackerAssigned.class);
		}
	}

