package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListOs;
 
/**
 * DAO interface for table: TrackerListOs.
 * @author autogenerated
 */
public interface TrackerListOsDao extends GenericDAO<TrackerListOs,  Integer>  {
	// constructor only
}

