package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAdminRequests;
 
/**
 * DAO interface for table: TrackerAdminRequests.
 * @author autogenerated
 */
public interface TrackerAdminRequestsDao extends GenericDAO<TrackerAdminRequests,  Integer>  {
	// constructor only
}

