package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerCache;
 
/**
 * DAO interface for table: TrackerCache.
 * @author autogenerated
 */
public interface TrackerCacheDao extends GenericDAO<TrackerCache,  Integer>  {
	// constructor only
}

