package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerSearches;
 
/**
 * DAO interface for table: TrackerSearches.
 * @author autogenerated
 */
public interface TrackerSearchesDao extends GenericDAO<TrackerSearches,  Integer>  {
	// constructor only
}

