package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerTableChangeLog;
 
/**
 * DAO interface for table: TrackerTableChangeLog.
 * @author autogenerated
 */
public interface TrackerTableChangeLogDao extends GenericDAO<TrackerTableChangeLog,  Integer>  {
	// constructor only
}

