package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUserMobileSetting;
 
/**
 * DAO interface for table: TrackerUserMobileSetting.
 * @author autogenerated
 */
public interface TrackerUserMobileSettingDao extends GenericDAO<TrackerUserMobileSetting,  Integer>  {
	// constructor only
}

