package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUsersInGroups;
 
/**
 * DAO interface for table: TrackerUsersInGroups.
 * @author autogenerated
 */
public interface TrackerUsersInGroupsDao extends GenericDAO<TrackerUsersInGroups,  Integer>  {
	// constructor only
}

