package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUserLocationLog;
 
/**
 * DAO interface for table: TrackerUserLocationLog.
 * @author autogenerated
 */
public interface TrackerUserLocationLogDao extends GenericDAO<TrackerUserLocationLog,  Integer>  {
	// constructor only
}

