package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerHistory;
 
/**
 * DAO interface for table: TrackerHistory.
 * @author autogenerated
 */
public interface TrackerHistoryDao extends GenericDAO<TrackerHistory,  Integer>  {
	// constructor only
}

