package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListStatus;
 
/**
 * DAO interface for table: TrackerListStatus.
 * @author autogenerated
 */
public interface TrackerListStatusDao extends GenericDAO<TrackerListStatus,  Integer>  {
	// constructor only
}

