package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListResolution;
 
/**
 * DAO interface for table: TrackerListResolution.
 * @author autogenerated
 */
public interface TrackerListResolutionDao extends GenericDAO<TrackerListResolution,  Integer>  {
	// constructor only
}

