package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerRelated;
 
/**
 * DAO interface for table: TrackerRelated.
 * @author autogenerated
 */
public interface TrackerRelatedDao extends GenericDAO<TrackerRelated,  Integer>  {
	// constructor only
}

