package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUsers;
 
/**
 * DAO interface for table: TrackerUsers.
 * @author autogenerated
 */
public interface TrackerUsersDao extends GenericDAO<TrackerUsers,  Integer>  {
	// constructor only
}

