package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerReminders;
 
/**
 * DAO interface for table: TrackerReminders.
 * @author autogenerated
 */
public interface TrackerRemindersDao extends GenericDAO<TrackerReminders,  Integer>  {
	// constructor only
}

