package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerGroups;
 
/**
 * DAO interface for table: TrackerGroups.
 * @author autogenerated
 */
public interface TrackerGroupsDao extends GenericDAO<TrackerGroups,  Integer>  {
	// constructor only
}

