package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerUserSession;
 
/**
 * DAO interface for table: TrackerUserSession.
 * @author autogenerated
 */
public interface TrackerUserSessionDao extends GenericDAO<TrackerUserSession,  Integer>  {
	// constructor only
}

