package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAttachments;
 
/**
 * DAO interface for table: TrackerAttachments.
 * @author autogenerated
 */
public interface TrackerAttachmentsDao extends GenericDAO<TrackerAttachments,  Integer>  {
	// constructor only
}

