package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerLocationGetType;
 
/**
 * DAO interface for table: TrackerLocationGetType.
 * @author autogenerated
 */
public interface TrackerLocationGetTypeDao extends GenericDAO<TrackerLocationGetType,  Integer>  {
	// constructor only
}

