package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerRegistrations;
 
/**
 * DAO interface for table: TrackerRegistrations.
 * @author autogenerated
 */
public interface TrackerRegistrationsDao extends GenericDAO<TrackerRegistrations,  Integer>  {
	// constructor only
}

