package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAssignedOld;
 
/**
 * DAO interface for table: TrackerAssignedOld.
 * @author autogenerated
 */
public interface TrackerAssignedOldDao extends GenericDAO<TrackerAssignedOld,  Integer>  {
	// constructor only
}

