package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerListTasktype;
 
/**
 * DAO interface for table: TrackerListTasktype.
 * @author autogenerated
 */
public interface TrackerListTasktypeDao extends GenericDAO<TrackerListTasktype,  Integer>  {
	// constructor only
}

