package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAssigned;
 
/**
 * DAO interface for table: TrackerAssigned.
 * @author autogenerated
 */
public interface TrackerAssignedDao extends GenericDAO<TrackerAssigned,  Integer>  {
	// constructor only
}

