package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerVotes;
 
/**
 * DAO interface for table: TrackerVotes.
 * @author autogenerated
 */
public interface TrackerVotesDao extends GenericDAO<TrackerVotes,  Integer>  {
	// constructor only
}

