package com.m2yazilim.tracker.dataaccess.model.dao.tracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerNotificationMessages;
 
/**
 * DAO interface for table: TrackerNotificationMessages.
 * @author autogenerated
 */
public interface TrackerNotificationMessagesDao extends GenericDAO<TrackerNotificationMessages,  Integer>  {
	// constructor only
}

