package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerNotificationRecipients;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerNotificationRecipientsDao;
 
 
/**
 * DAO for table: TrackerNotificationRecipients.
 * @author autogenerated
 */
@Repository
public class TrackerNotificationRecipientsDaoImpl extends GenericHibernateDaoImpl<TrackerNotificationRecipients, Integer> implements TrackerNotificationRecipientsDao {
	
	/** Constructor method. */
		public TrackerNotificationRecipientsDaoImpl() {
			super(TrackerNotificationRecipients.class);
		}
	}

