package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerAdminRequests;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerAdminRequestsDao;
 
 
/**
 * DAO for table: TrackerAdminRequests.
 * @author autogenerated
 */
@Repository
public class TrackerAdminRequestsDaoImpl extends GenericHibernateDaoImpl<TrackerAdminRequests, Integer> implements TrackerAdminRequestsDao {
	
	/** Constructor method. */
		public TrackerAdminRequestsDaoImpl() {
			super(TrackerAdminRequests.class);
		}
	}

