package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerCache;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerCacheDao;
 
 
/**
 * DAO for table: TrackerCache.
 * @author autogenerated
 */
@Repository
public class TrackerCacheDaoImpl extends GenericHibernateDaoImpl<TrackerCache, Integer> implements TrackerCacheDao {
	
	/** Constructor method. */
		public TrackerCacheDaoImpl() {
			super(TrackerCache.class);
		}
	}

