package com.m2yazilim.tracker.dataaccess.model.dao.tracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.m2yazilim.tracker.dataaccess.model.obj.tracker.TrackerRelated;
import org.springframework.stereotype.Repository;
import com.m2yazilim.tracker.dataaccess.model.dao.tracker.TrackerRelatedDao;
 
 
/**
 * DAO for table: TrackerRelated.
 * @author autogenerated
 */
@Repository
public class TrackerRelatedDaoImpl extends GenericHibernateDaoImpl<TrackerRelated, Integer> implements TrackerRelatedDao {
	
	/** Constructor method. */
		public TrackerRelatedDaoImpl() {
			super(TrackerRelated.class);
		}
	}

