package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerCacheDto generated by hbm2java
 */
public class TrackerCacheDto implements java.io.Serializable {

	private Integer id;
	private int version;
	private String type;
	private String content;
	private int topic;
	private int lastUpdated;
	private int projectId;
	private int maxItems;

	public TrackerCacheDto() {
	}

	public TrackerCacheDto(String type, String content, int topic,
			int lastUpdated, int projectId, int maxItems) {
		this.type = type;
		this.content = content;
		this.topic = topic;
		this.lastUpdated = lastUpdated;
		this.projectId = projectId;
		this.maxItems = maxItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getTopic() {
		return this.topic;
	}

	public void setTopic(int topic) {
		this.topic = topic;
	}

	public int getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(int lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public int getMaxItems() {
		return this.maxItems;
	}

	public void setMaxItems(int maxItems) {
		this.maxItems = maxItems;
	}

}
