package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerNotificationsDto generated by hbm2java
 */
public class TrackerNotificationsDto implements java.io.Serializable {

	private Integer notifyId;
	private int version;
	private int taskId;
	private int userId;

	public TrackerNotificationsDto() {
	}

	public TrackerNotificationsDto(int taskId, int userId) {
		this.taskId = taskId;
		this.userId = userId;
	}

	public Integer getNotifyId() {
		return this.notifyId;
	}

	public void setNotifyId(Integer notifyId) {
		this.notifyId = notifyId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
