package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerCommentsDto generated by hbm2java
 */
public class TrackerCommentsDto implements java.io.Serializable {

	private Integer commentId;
	private int version;
	private int taskId;
	private int dateAdded;
	private int userId;
	private String commentText;
	private int lastEditedTime;

	public TrackerCommentsDto() {
	}

	public TrackerCommentsDto(int taskId, int dateAdded, int userId,
			int lastEditedTime) {
		this.taskId = taskId;
		this.dateAdded = dateAdded;
		this.userId = userId;
		this.lastEditedTime = lastEditedTime;
	}

	public TrackerCommentsDto(int taskId, int dateAdded, int userId,
			String commentText, int lastEditedTime) {
		this.taskId = taskId;
		this.dateAdded = dateAdded;
		this.userId = userId;
		this.commentText = commentText;
		this.lastEditedTime = lastEditedTime;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(int dateAdded) {
		this.dateAdded = dateAdded;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getCommentText() {
		return this.commentText;
	}

	public void setCommentText(String commentText) {
		this.commentText = commentText;
	}

	public int getLastEditedTime() {
		return this.lastEditedTime;
	}

	public void setLastEditedTime(int lastEditedTime) {
		this.lastEditedTime = lastEditedTime;
	}

}
