package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerListResolutionDto generated by hbm2java
 */
public class TrackerListResolutionDto implements java.io.Serializable {

	private Integer resolutionId;
	private int version;
	private String resolutionName;
	private int listPosition;
	private int showInList;
	private int projectId;

	public TrackerListResolutionDto() {
	}

	public TrackerListResolutionDto(String resolutionName, int listPosition,
			int showInList, int projectId) {
		this.resolutionName = resolutionName;
		this.listPosition = listPosition;
		this.showInList = showInList;
		this.projectId = projectId;
	}

	public Integer getResolutionId() {
		return this.resolutionId;
	}

	public void setResolutionId(Integer resolutionId) {
		this.resolutionId = resolutionId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getResolutionName() {
		return this.resolutionName;
	}

	public void setResolutionName(String resolutionName) {
		this.resolutionName = resolutionName;
	}

	public int getListPosition() {
		return this.listPosition;
	}

	public void setListPosition(int listPosition) {
		this.listPosition = listPosition;
	}

	public int getShowInList() {
		return this.showInList;
	}

	public void setShowInList(int showInList) {
		this.showInList = showInList;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

}
