package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerTasksDto generated by hbm2java
 */
public class TrackerTasksDto implements java.io.Serializable {

	private Integer taskId;
	private int version;
	private int projectId;
	private int taskType;
	private int dateOpened;
	private int openedBy;
	private int isClosed;
	private int dateClosed;
	private int closedBy;
	private String closureComment;
	private String itemSummary;
	private String detailedDesc;
	private int itemStatus;
	private int resolutionReason;
	private int productCategory;
	private int productVersion;
	private int closedbyVersion;
	private int operatingSystem;
	private int taskSeverity;
	private int taskPriority;
	private int lastEditedBy;
	private int lastEditedTime;
	private int percentComplete;
	private int markPrivate;
	private int dueDate;
	private String anonEmail;
	private String taskToken;
	private String address;
	private Integer cityId;
	private String latitude;
	private String longitude;
	private int isCloseRequestSent = 0; // Default olarak kapatma istegi yoktur

	public TrackerTasksDto() {
	}

	public TrackerTasksDto(int projectId, int taskType, int dateOpened, int openedBy, int isClosed, int dateClosed,
			int closedBy, String itemSummary, int itemStatus, int resolutionReason, int productCategory,
			int productVersion, int closedbyVersion, int operatingSystem, int taskSeverity, int taskPriority,
			int lastEditedBy, int lastEditedTime, int percentComplete, int markPrivate, int dueDate, String anonEmail,
			String taskToken, int isCloseRequestSent) {
		this.projectId = projectId;
		this.taskType = taskType;
		this.dateOpened = dateOpened;
		this.openedBy = openedBy;
		this.isClosed = isClosed;
		this.dateClosed = dateClosed;
		this.closedBy = closedBy;
		this.itemSummary = itemSummary;
		this.itemStatus = itemStatus;
		this.resolutionReason = resolutionReason;
		this.productCategory = productCategory;
		this.productVersion = productVersion;
		this.closedbyVersion = closedbyVersion;
		this.operatingSystem = operatingSystem;
		this.taskSeverity = taskSeverity;
		this.taskPriority = taskPriority;
		this.lastEditedBy = lastEditedBy;
		this.lastEditedTime = lastEditedTime;
		this.percentComplete = percentComplete;
		this.markPrivate = markPrivate;
		this.dueDate = dueDate;
		this.anonEmail = anonEmail;
		this.taskToken = taskToken;
		this.isCloseRequestSent = isCloseRequestSent;
	}

	public TrackerTasksDto(int projectId, int taskType, int dateOpened, int openedBy, int isClosed, int dateClosed,
			int closedBy, String closureComment, String itemSummary, String detailedDesc, int itemStatus,
			int resolutionReason, int productCategory, int productVersion, int closedbyVersion, int operatingSystem,
			int taskSeverity, int taskPriority, int lastEditedBy, int lastEditedTime, int percentComplete,
			int markPrivate, int dueDate, String anonEmail, String taskToken, String address, Integer cityId,
			String latitude, String longitude, int isCloseRequestSent) {
		this.projectId = projectId;
		this.taskType = taskType;
		this.dateOpened = dateOpened;
		this.openedBy = openedBy;
		this.isClosed = isClosed;
		this.dateClosed = dateClosed;
		this.closedBy = closedBy;
		this.closureComment = closureComment;
		this.itemSummary = itemSummary;
		this.detailedDesc = detailedDesc;
		this.itemStatus = itemStatus;
		this.resolutionReason = resolutionReason;
		this.productCategory = productCategory;
		this.productVersion = productVersion;
		this.closedbyVersion = closedbyVersion;
		this.operatingSystem = operatingSystem;
		this.taskSeverity = taskSeverity;
		this.taskPriority = taskPriority;
		this.lastEditedBy = lastEditedBy;
		this.lastEditedTime = lastEditedTime;
		this.percentComplete = percentComplete;
		this.markPrivate = markPrivate;
		this.dueDate = dueDate;
		this.anonEmail = anonEmail;
		this.taskToken = taskToken;
		this.address = address;
		this.cityId = cityId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.isCloseRequestSent = isCloseRequestSent;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public int getTaskType() {
		return this.taskType;
	}

	public void setTaskType(int taskType) {
		this.taskType = taskType;
	}

	public int getDateOpened() {
		return this.dateOpened;
	}

	public void setDateOpened(int dateOpened) {
		this.dateOpened = dateOpened;
	}

	public int getOpenedBy() {
		return this.openedBy;
	}

	public void setOpenedBy(int openedBy) {
		this.openedBy = openedBy;
	}

	public int getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(int isClosed) {
		this.isClosed = isClosed;
	}

	public int getDateClosed() {
		return this.dateClosed;
	}

	public void setDateClosed(int dateClosed) {
		this.dateClosed = dateClosed;
	}

	public int getClosedBy() {
		return this.closedBy;
	}

	public void setClosedBy(int closedBy) {
		this.closedBy = closedBy;
	}

	public String getClosureComment() {
		return this.closureComment;
	}

	public void setClosureComment(String closureComment) {
		this.closureComment = closureComment;
	}

	public String getItemSummary() {
		return this.itemSummary;
	}

	public void setItemSummary(String itemSummary) {
		this.itemSummary = itemSummary;
	}

	public String getDetailedDesc() {
		return this.detailedDesc;
	}

	public void setDetailedDesc(String detailedDesc) {
		this.detailedDesc = detailedDesc;
	}

	public int getItemStatus() {
		return this.itemStatus;
	}

	public void setItemStatus(int itemStatus) {
		this.itemStatus = itemStatus;
	}

	public int getResolutionReason() {
		return this.resolutionReason;
	}

	public void setResolutionReason(int resolutionReason) {
		this.resolutionReason = resolutionReason;
	}

	public int getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(int productCategory) {
		this.productCategory = productCategory;
	}

	public int getProductVersion() {
		return this.productVersion;
	}

	public void setProductVersion(int productVersion) {
		this.productVersion = productVersion;
	}

	public int getClosedbyVersion() {
		return this.closedbyVersion;
	}

	public void setClosedbyVersion(int closedbyVersion) {
		this.closedbyVersion = closedbyVersion;
	}

	public int getOperatingSystem() {
		return this.operatingSystem;
	}

	public void setOperatingSystem(int operatingSystem) {
		this.operatingSystem = operatingSystem;
	}

	public int getTaskSeverity() {
		return this.taskSeverity;
	}

	public void setTaskSeverity(int taskSeverity) {
		this.taskSeverity = taskSeverity;
	}

	public int getTaskPriority() {
		return this.taskPriority;
	}

	public void setTaskPriority(int taskPriority) {
		this.taskPriority = taskPriority;
	}

	public int getLastEditedBy() {
		return this.lastEditedBy;
	}

	public void setLastEditedBy(int lastEditedBy) {
		this.lastEditedBy = lastEditedBy;
	}

	public int getLastEditedTime() {
		return this.lastEditedTime;
	}

	public void setLastEditedTime(int lastEditedTime) {
		this.lastEditedTime = lastEditedTime;
	}

	public int getPercentComplete() {
		return this.percentComplete;
	}

	public void setPercentComplete(int percentComplete) {
		this.percentComplete = percentComplete;
	}

	public int getMarkPrivate() {
		return this.markPrivate;
	}

	public void setMarkPrivate(int markPrivate) {
		this.markPrivate = markPrivate;
	}

	public int getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(int dueDate) {
		this.dueDate = dueDate;
	}

	public String getAnonEmail() {
		return this.anonEmail;
	}

	public void setAnonEmail(String anonEmail) {
		this.anonEmail = anonEmail;
	}

	public String getTaskToken() {
		return this.taskToken;
	}

	public void setTaskToken(String taskToken) {
		this.taskToken = taskToken;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public int getIsCloseRequestSent() {
		return isCloseRequestSent;
	}

	public void setIsCloseRequestSent(int isCloseRequestSent) {
		this.isCloseRequestSent = isCloseRequestSent;
	}

}
