package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerListStatusDto generated by hbm2java
 */
public class TrackerListStatusDto implements java.io.Serializable {

	private Integer statusId;
	private int version;
	private String statusName;
	private int listPosition;
	private int showInList;
	private int projectId;

	public TrackerListStatusDto() {
	}

	public TrackerListStatusDto(String statusName, int listPosition,
			int showInList, int projectId) {
		this.statusName = statusName;
		this.listPosition = listPosition;
		this.showInList = showInList;
		this.projectId = projectId;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public int getListPosition() {
		return this.listPosition;
	}

	public void setListPosition(int listPosition) {
		this.listPosition = listPosition;
	}

	public int getShowInList() {
		return this.showInList;
	}

	public void setShowInList(int showInList) {
		this.showInList = showInList;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

}
