package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerNotificationRecipientsDto generated by hbm2java
 */
public class TrackerNotificationRecipientsDto implements java.io.Serializable {

	private Integer recipientId;
	private int version;
	private int messageId;
	private String notifyMethod;
	private String notifyAddress;

	public TrackerNotificationRecipientsDto() {
	}

	public TrackerNotificationRecipientsDto(int messageId, String notifyMethod,
			String notifyAddress) {
		this.messageId = messageId;
		this.notifyMethod = notifyMethod;
		this.notifyAddress = notifyAddress;
	}

	public Integer getRecipientId() {
		return this.recipientId;
	}

	public void setRecipientId(Integer recipientId) {
		this.recipientId = recipientId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public String getNotifyMethod() {
		return this.notifyMethod;
	}

	public void setNotifyMethod(String notifyMethod) {
		this.notifyMethod = notifyMethod;
	}

	public String getNotifyAddress() {
		return this.notifyAddress;
	}

	public void setNotifyAddress(String notifyAddress) {
		this.notifyAddress = notifyAddress;
	}

}
