package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerUsersDto generated by hbm2java
 */
public class TrackerUsersDto implements java.io.Serializable {

	private Integer userId;
	private int version;
	private String userName;
	private String userPass;
	private String realName;
	private String jabberId;
	private String emailAddress;
	private int notifyType;
	private int notifyOwn;
	private int accountEnabled;
	private String dateformat;
	private String dateformatExtended;
	private String magicUrl;
	private int tasksPerpage;
	private int registerDate;
	private int timeZone;
	private int loginAttempts;
	private int lockUntil;

	public TrackerUsersDto() {
	}

	public TrackerUsersDto(String userName, String realName, String jabberId,
			String emailAddress, int notifyType, int notifyOwn,
			int accountEnabled, String dateformat, String dateformatExtended,
			String magicUrl, int tasksPerpage, int registerDate, int timeZone,
			int loginAttempts, int lockUntil) {
		this.userName = userName;
		this.realName = realName;
		this.jabberId = jabberId;
		this.emailAddress = emailAddress;
		this.notifyType = notifyType;
		this.notifyOwn = notifyOwn;
		this.accountEnabled = accountEnabled;
		this.dateformat = dateformat;
		this.dateformatExtended = dateformatExtended;
		this.magicUrl = magicUrl;
		this.tasksPerpage = tasksPerpage;
		this.registerDate = registerDate;
		this.timeZone = timeZone;
		this.loginAttempts = loginAttempts;
		this.lockUntil = lockUntil;
	}

	public TrackerUsersDto(String userName, String userPass, String realName,
			String jabberId, String emailAddress, int notifyType,
			int notifyOwn, int accountEnabled, String dateformat,
			String dateformatExtended, String magicUrl, int tasksPerpage,
			int registerDate, int timeZone, int loginAttempts, int lockUntil) {
		this.userName = userName;
		this.userPass = userPass;
		this.realName = realName;
		this.jabberId = jabberId;
		this.emailAddress = emailAddress;
		this.notifyType = notifyType;
		this.notifyOwn = notifyOwn;
		this.accountEnabled = accountEnabled;
		this.dateformat = dateformat;
		this.dateformatExtended = dateformatExtended;
		this.magicUrl = magicUrl;
		this.tasksPerpage = tasksPerpage;
		this.registerDate = registerDate;
		this.timeZone = timeZone;
		this.loginAttempts = loginAttempts;
		this.lockUntil = lockUntil;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getJabberId() {
		return this.jabberId;
	}

	public void setJabberId(String jabberId) {
		this.jabberId = jabberId;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public int getNotifyType() {
		return this.notifyType;
	}

	public void setNotifyType(int notifyType) {
		this.notifyType = notifyType;
	}

	public int getNotifyOwn() {
		return this.notifyOwn;
	}

	public void setNotifyOwn(int notifyOwn) {
		this.notifyOwn = notifyOwn;
	}

	public int getAccountEnabled() {
		return this.accountEnabled;
	}

	public void setAccountEnabled(int accountEnabled) {
		this.accountEnabled = accountEnabled;
	}

	public String getDateformat() {
		return this.dateformat;
	}

	public void setDateformat(String dateformat) {
		this.dateformat = dateformat;
	}

	public String getDateformatExtended() {
		return this.dateformatExtended;
	}

	public void setDateformatExtended(String dateformatExtended) {
		this.dateformatExtended = dateformatExtended;
	}

	public String getMagicUrl() {
		return this.magicUrl;
	}

	public void setMagicUrl(String magicUrl) {
		this.magicUrl = magicUrl;
	}

	public int getTasksPerpage() {
		return this.tasksPerpage;
	}

	public void setTasksPerpage(int tasksPerpage) {
		this.tasksPerpage = tasksPerpage;
	}

	public int getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(int registerDate) {
		this.registerDate = registerDate;
	}

	public int getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(int timeZone) {
		this.timeZone = timeZone;
	}

	public int getLoginAttempts() {
		return this.loginAttempts;
	}

	public void setLoginAttempts(int loginAttempts) {
		this.loginAttempts = loginAttempts;
	}

	public int getLockUntil() {
		return this.lockUntil;
	}

	public void setLockUntil(int lockUntil) {
		this.lockUntil = lockUntil;
	}

}
