package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerHistoryDto generated by hbm2java
 */
public class TrackerHistoryDto implements java.io.Serializable {

	private Integer historyId;
	private int version;
	private int taskId;
	private int userId;
	private int eventDate;
	private int eventType;
	private String fieldChanged;
	private String oldValue;
	private String newValue;

	public TrackerHistoryDto() {
	}

	public TrackerHistoryDto(int taskId, int userId, int eventDate,
			int eventType, String fieldChanged) {
		this.taskId = taskId;
		this.userId = userId;
		this.eventDate = eventDate;
		this.eventType = eventType;
		this.fieldChanged = fieldChanged;
	}

	public TrackerHistoryDto(int taskId, int userId, int eventDate,
			int eventType, String fieldChanged, String oldValue, String newValue) {
		this.taskId = taskId;
		this.userId = userId;
		this.eventDate = eventDate;
		this.eventType = eventType;
		this.fieldChanged = fieldChanged;
		this.oldValue = oldValue;
		this.newValue = newValue;
	}

	public Integer getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(Integer historyId) {
		this.historyId = historyId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(int eventDate) {
		this.eventDate = eventDate;
	}

	public int getEventType() {
		return this.eventType;
	}

	public void setEventType(int eventType) {
		this.eventType = eventType;
	}

	public String getFieldChanged() {
		return this.fieldChanged;
	}

	public void setFieldChanged(String fieldChanged) {
		this.fieldChanged = fieldChanged;
	}

	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

}
