package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerVotesDto generated by hbm2java
 */
public class TrackerVotesDto implements java.io.Serializable {

	private Integer voteId;
	private int version;
	private int userId;
	private int taskId;
	private int dateTime;

	public TrackerVotesDto() {
	}

	public TrackerVotesDto(int userId, int taskId, int dateTime) {
		this.userId = userId;
		this.taskId = taskId;
		this.dateTime = dateTime;
	}

	public Integer getVoteId() {
		return this.voteId;
	}

	public void setVoteId(Integer voteId) {
		this.voteId = voteId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(int dateTime) {
		this.dateTime = dateTime;
	}

}
