package com.m2yazilim.tracker.dto;

// Generated Jan 12, 2013 9:43:39 AM by Hibernate Tools 4.0.0

/**
 * TrackerLocationGetTypeDto generated by hbm2java
 */
public class TrackerLocationGetTypeDto implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private String name;
	private String description;

	public TrackerLocationGetTypeDto() {
	}

	public TrackerLocationGetTypeDto(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
