package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerPrefsDto generated by hbm2java
 */
public class TrackerPrefsDto implements java.io.Serializable {

	private Integer prefId;
	private String prefName;
	private String prefValue;

	public TrackerPrefsDto() {
	}

	public TrackerPrefsDto(String prefName, String prefValue) {
		this.prefName = prefName;
		this.prefValue = prefValue;
	}

	public Integer getPrefId() {
		return this.prefId;
	}

	public void setPrefId(Integer prefId) {
		this.prefId = prefId;
	}

	public String getPrefName() {
		return this.prefName;
	}

	public void setPrefName(String prefName) {
		this.prefName = prefName;
	}

	public String getPrefValue() {
		return this.prefValue;
	}

	public void setPrefValue(String prefValue) {
		this.prefValue = prefValue;
	}

}
