package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerDependenciesDto generated by hbm2java
 */
public class TrackerDependenciesDto implements java.io.Serializable {

	private Integer dependId;
	private int version;
	private int taskId;
	private int depTaskId;

	public TrackerDependenciesDto() {
	}

	public TrackerDependenciesDto(int taskId, int depTaskId) {
		this.taskId = taskId;
		this.depTaskId = depTaskId;
	}

	public Integer getDependId() {
		return this.dependId;
	}

	public void setDependId(Integer dependId) {
		this.dependId = dependId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getDepTaskId() {
		return this.depTaskId;
	}

	public void setDepTaskId(int depTaskId) {
		this.depTaskId = depTaskId;
	}

}
