package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerNotificationMessagesDto generated by hbm2java
 */
public class TrackerNotificationMessagesDto implements java.io.Serializable {

	private Integer messageId;
	private int version;
	private String messageSubject;
	private String messageBody;
	private int timeCreated;

	public TrackerNotificationMessagesDto() {
	}

	public TrackerNotificationMessagesDto(int timeCreated) {
		this.timeCreated = timeCreated;
	}

	public TrackerNotificationMessagesDto(String messageSubject,
			String messageBody, int timeCreated) {
		this.messageSubject = messageSubject;
		this.messageBody = messageBody;
		this.timeCreated = timeCreated;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getMessageSubject() {
		return this.messageSubject;
	}

	public void setMessageSubject(String messageSubject) {
		this.messageSubject = messageSubject;
	}

	public String getMessageBody() {
		return this.messageBody;
	}

	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody;
	}

	public int getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(int timeCreated) {
		this.timeCreated = timeCreated;
	}

}
