package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerRelatedDto generated by hbm2java
 */
public class TrackerRelatedDto implements java.io.Serializable {

	private Integer relatedId;
	private int version;
	private int thisTask;
	private int relatedTask;
	private int isDuplicate;

	public TrackerRelatedDto() {
	}

	public TrackerRelatedDto(int thisTask, int relatedTask, int isDuplicate) {
		this.thisTask = thisTask;
		this.relatedTask = relatedTask;
		this.isDuplicate = isDuplicate;
	}

	public Integer getRelatedId() {
		return this.relatedId;
	}

	public void setRelatedId(Integer relatedId) {
		this.relatedId = relatedId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getThisTask() {
		return this.thisTask;
	}

	public void setThisTask(int thisTask) {
		this.thisTask = thisTask;
	}

	public int getRelatedTask() {
		return this.relatedTask;
	}

	public void setRelatedTask(int relatedTask) {
		this.relatedTask = relatedTask;
	}

	public int getIsDuplicate() {
		return this.isDuplicate;
	}

	public void setIsDuplicate(int isDuplicate) {
		this.isDuplicate = isDuplicate;
	}

}
