package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerAdminRequestsDto generated by hbm2java
 */
public class TrackerAdminRequestsDto implements java.io.Serializable {

	private Integer requestId;
	private int version;
	private int projectId;
	private int taskId;
	private int submittedBy;
	private int requestType;
	private String reasonGiven;
	private int timeSubmitted;
	private int resolvedBy;
	private int timeResolved;
	private String denyReason;

	public TrackerAdminRequestsDto() {
	}

	public TrackerAdminRequestsDto(int projectId, int taskId, int submittedBy,
			int requestType, int timeSubmitted, int resolvedBy, int timeResolved) {
		this.projectId = projectId;
		this.taskId = taskId;
		this.submittedBy = submittedBy;
		this.requestType = requestType;
		this.timeSubmitted = timeSubmitted;
		this.resolvedBy = resolvedBy;
		this.timeResolved = timeResolved;
	}

	public TrackerAdminRequestsDto(int projectId, int taskId, int submittedBy,
			int requestType, String reasonGiven, int timeSubmitted,
			int resolvedBy, int timeResolved, String denyReason) {
		this.projectId = projectId;
		this.taskId = taskId;
		this.submittedBy = submittedBy;
		this.requestType = requestType;
		this.reasonGiven = reasonGiven;
		this.timeSubmitted = timeSubmitted;
		this.resolvedBy = resolvedBy;
		this.timeResolved = timeResolved;
		this.denyReason = denyReason;
	}

	public Integer getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getSubmittedBy() {
		return this.submittedBy;
	}

	public void setSubmittedBy(int submittedBy) {
		this.submittedBy = submittedBy;
	}

	public int getRequestType() {
		return this.requestType;
	}

	public void setRequestType(int requestType) {
		this.requestType = requestType;
	}

	public String getReasonGiven() {
		return this.reasonGiven;
	}

	public void setReasonGiven(String reasonGiven) {
		this.reasonGiven = reasonGiven;
	}

	public int getTimeSubmitted() {
		return this.timeSubmitted;
	}

	public void setTimeSubmitted(int timeSubmitted) {
		this.timeSubmitted = timeSubmitted;
	}

	public int getResolvedBy() {
		return this.resolvedBy;
	}

	public void setResolvedBy(int resolvedBy) {
		this.resolvedBy = resolvedBy;
	}

	public int getTimeResolved() {
		return this.timeResolved;
	}

	public void setTimeResolved(int timeResolved) {
		this.timeResolved = timeResolved;
	}

	public String getDenyReason() {
		return this.denyReason;
	}

	public void setDenyReason(String denyReason) {
		this.denyReason = denyReason;
	}

}
