package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerGroupsDto generated by hbm2java
 */
public class TrackerGroupsDto implements java.io.Serializable {

	private Integer groupId;
	private int version;
	private String groupName;
	private String groupDesc;
	private int projectId;
	private int isAdmin;
	private int manageProject;
	private int viewTasks;
	private int openNewTasks;
	private int modifyOwnTasks;
	private int modifyAllTasks;
	private int viewComments;
	private int addComments;
	private int editComments;
	private int editOwnComments;
	private int deleteComments;
	private int createAttachments;
	private int deleteAttachments;
	private int viewHistory;
	private int closeOwnTasks;
	private int closeOtherTasks;
	private int assignToSelf;
	private int assignOthersToSelf;
	private int addToAssignees;
	private int viewReports;
	private int addVotes;
	private int editAssignments;
	private int showAsAssignees;
	private int groupOpen;

	public TrackerGroupsDto() {
	}

	public TrackerGroupsDto(String groupName, String groupDesc, int projectId,
			int isAdmin, int manageProject, int viewTasks, int openNewTasks,
			int modifyOwnTasks, int modifyAllTasks, int viewComments,
			int addComments, int editComments, int editOwnComments,
			int deleteComments, int createAttachments, int deleteAttachments,
			int viewHistory, int closeOwnTasks, int closeOtherTasks,
			int assignToSelf, int assignOthersToSelf, int addToAssignees,
			int viewReports, int addVotes, int editAssignments,
			int showAsAssignees, int groupOpen) {
		this.groupName = groupName;
		this.groupDesc = groupDesc;
		this.projectId = projectId;
		this.isAdmin = isAdmin;
		this.manageProject = manageProject;
		this.viewTasks = viewTasks;
		this.openNewTasks = openNewTasks;
		this.modifyOwnTasks = modifyOwnTasks;
		this.modifyAllTasks = modifyAllTasks;
		this.viewComments = viewComments;
		this.addComments = addComments;
		this.editComments = editComments;
		this.editOwnComments = editOwnComments;
		this.deleteComments = deleteComments;
		this.createAttachments = createAttachments;
		this.deleteAttachments = deleteAttachments;
		this.viewHistory = viewHistory;
		this.closeOwnTasks = closeOwnTasks;
		this.closeOtherTasks = closeOtherTasks;
		this.assignToSelf = assignToSelf;
		this.assignOthersToSelf = assignOthersToSelf;
		this.addToAssignees = addToAssignees;
		this.viewReports = viewReports;
		this.addVotes = addVotes;
		this.editAssignments = editAssignments;
		this.showAsAssignees = showAsAssignees;
		this.groupOpen = groupOpen;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public int getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(int isAdmin) {
		this.isAdmin = isAdmin;
	}

	public int getManageProject() {
		return this.manageProject;
	}

	public void setManageProject(int manageProject) {
		this.manageProject = manageProject;
	}

	public int getViewTasks() {
		return this.viewTasks;
	}

	public void setViewTasks(int viewTasks) {
		this.viewTasks = viewTasks;
	}

	public int getOpenNewTasks() {
		return this.openNewTasks;
	}

	public void setOpenNewTasks(int openNewTasks) {
		this.openNewTasks = openNewTasks;
	}

	public int getModifyOwnTasks() {
		return this.modifyOwnTasks;
	}

	public void setModifyOwnTasks(int modifyOwnTasks) {
		this.modifyOwnTasks = modifyOwnTasks;
	}

	public int getModifyAllTasks() {
		return this.modifyAllTasks;
	}

	public void setModifyAllTasks(int modifyAllTasks) {
		this.modifyAllTasks = modifyAllTasks;
	}

	public int getViewComments() {
		return this.viewComments;
	}

	public void setViewComments(int viewComments) {
		this.viewComments = viewComments;
	}

	public int getAddComments() {
		return this.addComments;
	}

	public void setAddComments(int addComments) {
		this.addComments = addComments;
	}

	public int getEditComments() {
		return this.editComments;
	}

	public void setEditComments(int editComments) {
		this.editComments = editComments;
	}

	public int getEditOwnComments() {
		return this.editOwnComments;
	}

	public void setEditOwnComments(int editOwnComments) {
		this.editOwnComments = editOwnComments;
	}

	public int getDeleteComments() {
		return this.deleteComments;
	}

	public void setDeleteComments(int deleteComments) {
		this.deleteComments = deleteComments;
	}

	public int getCreateAttachments() {
		return this.createAttachments;
	}

	public void setCreateAttachments(int createAttachments) {
		this.createAttachments = createAttachments;
	}

	public int getDeleteAttachments() {
		return this.deleteAttachments;
	}

	public void setDeleteAttachments(int deleteAttachments) {
		this.deleteAttachments = deleteAttachments;
	}

	public int getViewHistory() {
		return this.viewHistory;
	}

	public void setViewHistory(int viewHistory) {
		this.viewHistory = viewHistory;
	}

	public int getCloseOwnTasks() {
		return this.closeOwnTasks;
	}

	public void setCloseOwnTasks(int closeOwnTasks) {
		this.closeOwnTasks = closeOwnTasks;
	}

	public int getCloseOtherTasks() {
		return this.closeOtherTasks;
	}

	public void setCloseOtherTasks(int closeOtherTasks) {
		this.closeOtherTasks = closeOtherTasks;
	}

	public int getAssignToSelf() {
		return this.assignToSelf;
	}

	public void setAssignToSelf(int assignToSelf) {
		this.assignToSelf = assignToSelf;
	}

	public int getAssignOthersToSelf() {
		return this.assignOthersToSelf;
	}

	public void setAssignOthersToSelf(int assignOthersToSelf) {
		this.assignOthersToSelf = assignOthersToSelf;
	}

	public int getAddToAssignees() {
		return this.addToAssignees;
	}

	public void setAddToAssignees(int addToAssignees) {
		this.addToAssignees = addToAssignees;
	}

	public int getViewReports() {
		return this.viewReports;
	}

	public void setViewReports(int viewReports) {
		this.viewReports = viewReports;
	}

	public int getAddVotes() {
		return this.addVotes;
	}

	public void setAddVotes(int addVotes) {
		this.addVotes = addVotes;
	}

	public int getEditAssignments() {
		return this.editAssignments;
	}

	public void setEditAssignments(int editAssignments) {
		this.editAssignments = editAssignments;
	}

	public int getShowAsAssignees() {
		return this.showAsAssignees;
	}

	public void setShowAsAssignees(int showAsAssignees) {
		this.showAsAssignees = showAsAssignees;
	}

	public int getGroupOpen() {
		return this.groupOpen;
	}

	public void setGroupOpen(int groupOpen) {
		this.groupOpen = groupOpen;
	}

}
