package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerRemindersDto generated by hbm2java
 */
public class TrackerRemindersDto implements java.io.Serializable {

	private Integer reminderId;
	private int version;
	private int taskId;
	private int toUserId;
	private int fromUserId;
	private int startTime;
	private int howOften;
	private int lastSent;
	private String reminderMessage;

	public TrackerRemindersDto() {
	}

	public TrackerRemindersDto(int taskId, int toUserId, int fromUserId,
			int startTime, int howOften, int lastSent) {
		this.taskId = taskId;
		this.toUserId = toUserId;
		this.fromUserId = fromUserId;
		this.startTime = startTime;
		this.howOften = howOften;
		this.lastSent = lastSent;
	}

	public TrackerRemindersDto(int taskId, int toUserId, int fromUserId,
			int startTime, int howOften, int lastSent, String reminderMessage) {
		this.taskId = taskId;
		this.toUserId = toUserId;
		this.fromUserId = fromUserId;
		this.startTime = startTime;
		this.howOften = howOften;
		this.lastSent = lastSent;
		this.reminderMessage = reminderMessage;
	}

	public Integer getReminderId() {
		return this.reminderId;
	}

	public void setReminderId(Integer reminderId) {
		this.reminderId = reminderId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getToUserId() {
		return this.toUserId;
	}

	public void setToUserId(int toUserId) {
		this.toUserId = toUserId;
	}

	public int getFromUserId() {
		return this.fromUserId;
	}

	public void setFromUserId(int fromUserId) {
		this.fromUserId = fromUserId;
	}

	public int getStartTime() {
		return this.startTime;
	}

	public void setStartTime(int startTime) {
		this.startTime = startTime;
	}

	public int getHowOften() {
		return this.howOften;
	}

	public void setHowOften(int howOften) {
		this.howOften = howOften;
	}

	public int getLastSent() {
		return this.lastSent;
	}

	public void setLastSent(int lastSent) {
		this.lastSent = lastSent;
	}

	public String getReminderMessage() {
		return this.reminderMessage;
	}

	public void setReminderMessage(String reminderMessage) {
		this.reminderMessage = reminderMessage;
	}

}
