package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerAssignedDto generated by hbm2java
 */
public class TrackerAssignedDto implements java.io.Serializable {

	private Integer assignedId;
	private int version;
	private int taskId;
	private int userId;

	public TrackerAssignedDto() {
	}

	public TrackerAssignedDto(int taskId, int userId) {
		this.taskId = taskId;
		this.userId = userId;
	}

	public Integer getAssignedId() {
		return this.assignedId;
	}

	public void setAssignedId(Integer assignedId) {
		this.assignedId = assignedId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
