package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerListVersionDto generated by hbm2java
 */
public class TrackerListVersionDto implements java.io.Serializable {

	private Integer versionId;
	private int version;
	private int projectId;
	private String versionName;
	private int listPosition;
	private int showInList;
	private int versionTense;

	public TrackerListVersionDto() {
	}

	public TrackerListVersionDto(int projectId, String versionName,
			int listPosition, int showInList, int versionTense) {
		this.projectId = projectId;
		this.versionName = versionName;
		this.listPosition = listPosition;
		this.showInList = showInList;
		this.versionTense = versionTense;
	}

	public Integer getVersionId() {
		return this.versionId;
	}

	public void setVersionId(Integer versionId) {
		this.versionId = versionId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	public int getListPosition() {
		return this.listPosition;
	}

	public void setListPosition(int listPosition) {
		this.listPosition = listPosition;
	}

	public int getShowInList() {
		return this.showInList;
	}

	public void setShowInList(int showInList) {
		this.showInList = showInList;
	}

	public int getVersionTense() {
		return this.versionTense;
	}

	public void setVersionTense(int versionTense) {
		this.versionTense = versionTense;
	}

}
