package com.m2yazilim.tracker.dto;

// Generated Nov 21, 2012 12:58:59 PM by Hibernate Tools 4.0.0

/**
 * TrackerListOsDto generated by hbm2java
 */
public class TrackerListOsDto implements java.io.Serializable {

	private Integer osId;
	private int version;
	private int projectId;
	private String osName;
	private int listPosition;
	private int showInList;

	public TrackerListOsDto() {
	}

	public TrackerListOsDto(int projectId, String osName, int listPosition,
			int showInList) {
		this.projectId = projectId;
		this.osName = osName;
		this.listPosition = listPosition;
		this.showInList = showInList;
	}

	public Integer getOsId() {
		return this.osId;
	}

	public void setOsId(Integer osId) {
		this.osId = osId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getOsName() {
		return this.osName;
	}

	public void setOsName(String osName) {
		this.osName = osName;
	}

	public int getListPosition() {
		return this.listPosition;
	}

	public void setListPosition(int listPosition) {
		this.listPosition = listPosition;
	}

	public int getShowInList() {
		return this.showInList;
	}

	public void setShowInList(int showInList) {
		this.showInList = showInList;
	}

}
