package com.m2yazilim.tracker.dataaccess.factories.tracker;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import com.m2yazilim.tracker.dataaccess.model.dao.tracker.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateTrackerDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateTrackerDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateTrackerDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateTrackerDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a TrackerAdminRequestsDao instance.
	 * 
	 * @return a TrackerAdminRequestsDao instance
	 */
	public static TrackerAdminRequestsDao getTrackerAdminRequestsDao() {
		return (TrackerAdminRequestsDao) getBean("trackerAdminRequestsDaoImpl"); 
	}
	/**
	 * Returns a TrackerAssignedDao instance.
	 * 
	 * @return a TrackerAssignedDao instance
	 */
	public static TrackerAssignedDao getTrackerAssignedDao() {
		return (TrackerAssignedDao) getBean("trackerAssignedDaoImpl"); 
	}
	/**
	 * Returns a TrackerAttachmentsDao instance.
	 * 
	 * @return a TrackerAttachmentsDao instance
	 */
	public static TrackerAttachmentsDao getTrackerAttachmentsDao() {
		return (TrackerAttachmentsDao) getBean("trackerAttachmentsDaoImpl"); 
	}
	/**
	 * Returns a TrackerCacheDao instance.
	 * 
	 * @return a TrackerCacheDao instance
	 */
	public static TrackerCacheDao getTrackerCacheDao() {
		return (TrackerCacheDao) getBean("trackerCacheDaoImpl"); 
	}
	/**
	 * Returns a TrackerCityDao instance.
	 * 
	 * @return a TrackerCityDao instance
	 */
	public static TrackerCityDao getTrackerCityDao() {
		return (TrackerCityDao) getBean("trackerCityDaoImpl"); 
	}
	/**
	 * Returns a TrackerCommentsDao instance.
	 * 
	 * @return a TrackerCommentsDao instance
	 */
	public static TrackerCommentsDao getTrackerCommentsDao() {
		return (TrackerCommentsDao) getBean("trackerCommentsDaoImpl"); 
	}
	/**
	 * Returns a TrackerDependenciesDao instance.
	 * 
	 * @return a TrackerDependenciesDao instance
	 */
	public static TrackerDependenciesDao getTrackerDependenciesDao() {
		return (TrackerDependenciesDao) getBean("trackerDependenciesDaoImpl"); 
	}
	/**
	 * Returns a TrackerGroupsDao instance.
	 * 
	 * @return a TrackerGroupsDao instance
	 */
	public static TrackerGroupsDao getTrackerGroupsDao() {
		return (TrackerGroupsDao) getBean("trackerGroupsDaoImpl"); 
	}
	/**
	 * Returns a TrackerHistoryDao instance.
	 * 
	 * @return a TrackerHistoryDao instance
	 */
	public static TrackerHistoryDao getTrackerHistoryDao() {
		return (TrackerHistoryDao) getBean("trackerHistoryDaoImpl"); 
	}
	/**
	 * Returns a TrackerListCategoryDao instance.
	 * 
	 * @return a TrackerListCategoryDao instance
	 */
	public static TrackerListCategoryDao getTrackerListCategoryDao() {
		return (TrackerListCategoryDao) getBean("trackerListCategoryDaoImpl"); 
	}
	/**
	 * Returns a TrackerListOsDao instance.
	 * 
	 * @return a TrackerListOsDao instance
	 */
	public static TrackerListOsDao getTrackerListOsDao() {
		return (TrackerListOsDao) getBean("trackerListOsDaoImpl"); 
	}
	/**
	 * Returns a TrackerListResolutionDao instance.
	 * 
	 * @return a TrackerListResolutionDao instance
	 */
	public static TrackerListResolutionDao getTrackerListResolutionDao() {
		return (TrackerListResolutionDao) getBean("trackerListResolutionDaoImpl"); 
	}
	/**
	 * Returns a TrackerListStatusDao instance.
	 * 
	 * @return a TrackerListStatusDao instance
	 */
	public static TrackerListStatusDao getTrackerListStatusDao() {
		return (TrackerListStatusDao) getBean("trackerListStatusDaoImpl"); 
	}
	/**
	 * Returns a TrackerListTasktypeDao instance.
	 * 
	 * @return a TrackerListTasktypeDao instance
	 */
	public static TrackerListTasktypeDao getTrackerListTasktypeDao() {
		return (TrackerListTasktypeDao) getBean("trackerListTasktypeDaoImpl"); 
	}
	/**
	 * Returns a TrackerListVersionDao instance.
	 * 
	 * @return a TrackerListVersionDao instance
	 */
	public static TrackerListVersionDao getTrackerListVersionDao() {
		return (TrackerListVersionDao) getBean("trackerListVersionDaoImpl"); 
	}
	/**
	 * Returns a TrackerNotificationMessagesDao instance.
	 * 
	 * @return a TrackerNotificationMessagesDao instance
	 */
	public static TrackerNotificationMessagesDao getTrackerNotificationMessagesDao() {
		return (TrackerNotificationMessagesDao) getBean("trackerNotificationMessagesDaoImpl"); 
	}
	/**
	 * Returns a TrackerNotificationRecipientsDao instance.
	 * 
	 * @return a TrackerNotificationRecipientsDao instance
	 */
	public static TrackerNotificationRecipientsDao getTrackerNotificationRecipientsDao() {
		return (TrackerNotificationRecipientsDao) getBean("trackerNotificationRecipientsDaoImpl"); 
	}
	/**
	 * Returns a TrackerNotificationsDao instance.
	 * 
	 * @return a TrackerNotificationsDao instance
	 */
	public static TrackerNotificationsDao getTrackerNotificationsDao() {
		return (TrackerNotificationsDao) getBean("trackerNotificationsDaoImpl"); 
	}
	/**
	 * Returns a TrackerPrefsDao instance.
	 * 
	 * @return a TrackerPrefsDao instance
	 */
	public static TrackerPrefsDao getTrackerPrefsDao() {
		return (TrackerPrefsDao) getBean("trackerPrefsDaoImpl"); 
	}
	/**
	 * Returns a TrackerProjectsDao instance.
	 * 
	 * @return a TrackerProjectsDao instance
	 */
	public static TrackerProjectsDao getTrackerProjectsDao() {
		return (TrackerProjectsDao) getBean("trackerProjectsDaoImpl"); 
	}
	/**
	 * Returns a TrackerRegistrationsDao instance.
	 * 
	 * @return a TrackerRegistrationsDao instance
	 */
	public static TrackerRegistrationsDao getTrackerRegistrationsDao() {
		return (TrackerRegistrationsDao) getBean("trackerRegistrationsDaoImpl"); 
	}
	/**
	 * Returns a TrackerRelatedDao instance.
	 * 
	 * @return a TrackerRelatedDao instance
	 */
	public static TrackerRelatedDao getTrackerRelatedDao() {
		return (TrackerRelatedDao) getBean("trackerRelatedDaoImpl"); 
	}
	/**
	 * Returns a TrackerRemindersDao instance.
	 * 
	 * @return a TrackerRemindersDao instance
	 */
	public static TrackerRemindersDao getTrackerRemindersDao() {
		return (TrackerRemindersDao) getBean("trackerRemindersDaoImpl"); 
	}
	/**
	 * Returns a TrackerSearchesDao instance.
	 * 
	 * @return a TrackerSearchesDao instance
	 */
	public static TrackerSearchesDao getTrackerSearchesDao() {
		return (TrackerSearchesDao) getBean("trackerSearchesDaoImpl"); 
	}
	/**
	 * Returns a TrackerTasksDao instance.
	 * 
	 * @return a TrackerTasksDao instance
	 */
	public static TrackerTasksDao getTrackerTasksDao() {
		return (TrackerTasksDao) getBean("trackerTasksDaoImpl"); 
	}
	/**
	 * Returns a TrackerUsersDao instance.
	 * 
	 * @return a TrackerUsersDao instance
	 */
	public static TrackerUsersDao getTrackerUsersDao() {
		return (TrackerUsersDao) getBean("trackerUsersDaoImpl"); 
	}
	/**
	 * Returns a TrackerUsersInGroupsDao instance.
	 * 
	 * @return a TrackerUsersInGroupsDao instance
	 */
	public static TrackerUsersInGroupsDao getTrackerUsersInGroupsDao() {
		return (TrackerUsersInGroupsDao) getBean("trackerUsersInGroupsDaoImpl"); 
	}
	/**
	 * Returns a TrackerVotesDao instance.
	 * 
	 * @return a TrackerVotesDao instance
	 */
	public static TrackerVotesDao getTrackerVotesDao() {
		return (TrackerVotesDao) getBean("trackerVotesDaoImpl"); 
	}

}
